#!/bin/bash

set -euo pipefail
. /.functions

set_or_default SSL_DIR "/.ssl"

require_exe openssl sha256sum

doing "Validating the existing certificates and keys"
is_dir "${SSL_DIR}"

PWFILE="${SSL_DIR}/keystore.pass"
[ -v ACME_KEYSTORE_PASSWORD_FILE ] && PWFILE="${ACME_KEYSTORE_PASSWORD_FILE}"

[ -n "${PWFILE}" ] || fail "The password file specification cannot be empty"
[ -s "${PWFILE}" ] || fail "The password file must be a non-empty file"

# Check that all the files are there
BASE_FILES=(
	"${SSL_DIR}/ca-root.pem"
	"${SSL_DIR}/ca-int.pem"
	"${SSL_DIR}/cert.key.enc"
	"${SSL_DIR}/cert.pem"
	"${PWFILE}"
)

for f in "${BASE_FILES[@]}" ; do
	is_file_readable "${f}"
	[ -s "${f}" ] || fail "The file [${f}] is of length 0"
done

# Check that the key is valid, and that the password decrypts it
openssl rsa -check -noout -in "${SSL_DIR}/cert.key.enc" -passin file:"${PWFILE}" &>/dev/null || fail "The private key is not valid, or could not be decrypted with the stored password"

# Check that the private and public keys match
read PRIVATE rest < <(openssl rsa -modulus -noout -in "${SSL_DIR}/cert.key.enc" -passin file:"${PWFILE}" | sha256sum)
read PUBLIC rest < <(openssl x509 -modulus -noout -in "${SSL_DIR}/cert.pem" | sha256sum)
[ "${PUBLIC}" == "${PRIVATE}" ] || fail "The modulus for the private and public keys did not match."

# Is the int cert signed by the root pem?
openssl verify -CAfile "${SSL_DIR}/ca-root.pem" "${SSL_DIR}/ca-int.pem" &>/dev/null || fail "The intermediate CA is not signed by the root CA"
openssl verify -CAfile <(cat "${SSL_DIR}/ca-int.pem" "${SSL_DIR}/ca-root.pem") "${SSL_DIR}/cert.pem" &>/dev/null || fail "The certificate isn't signed by the intermediate CA"

# Are the int and root certs deployed to the anchor directories?
set_or_default ANCHORS "/etc/pki/ca-trust/source/anchors"

for n in ca-int ca-root ; do
	MASTER="${SSL_DIR}/${n}.pem"
	ANCHOR="${ANCHORS}/${n}.crt"
	[ -f "${MASTER}" ] || fail "The master certificate [${MASTER}] does not exist"
	[ -f "${ANCHOR}" ] || fail "The anchor certificate [${ANCHOR}] does not exist"

	read A REST < <(sha256sum "${MASTER}")
	read B REST < <(sha256sum "${ANCHOR}")

	[ "${A}" == "${B}" ] || fail "The SHA-256 sums for [${MASTER}] and [${ANCHOR}] don't match: [${A}] != [${B}]"
done

ok "Certificate validation at [${SSL_DIR}] complete!"
exit 0
