#!/bin/bash

[ ${#} -lt 1 ] && echo -e "usage: ${BASH_ARGV0} rpm1 [rpm2 rpm3 ... rpmN]" && exit 1

list_versions() {
	for n in "${@}" ; do
		[ -f "${n}" ] || continue
		/usr/bin/rpm -qp --queryformat "%{NAME}/%{VERSION}/%{RELEASE}=${n}\n" "${n}"
	done 2>/dev/null
}

NAME=""
while read VERSION ; do
	# Get the version information
	IFS="/" read name version release <<< "${VERSION}"

	# Make sure we got all the data
	[ -n "${name}" ] || continue
	[ -n "${version}" ] || continue
	[ -n "${release}" ] || continue

	# Use the name for the first package as the name required of all packages
	[ -z "${NAME}" ] && NAME="${name}"

	# If they're not the same package, skip it
	[ "${NAME}" != "${name}" ] && continue


	# Split out the release into the release and the filename
	file="${release#*=}"
	release="${release%%=*}"

	echo "${version}/${release}/${file}"
done < <(list_versions "${@}") | \
	/usr/bin/sort -V -t / -k 1,2 | \
	/usr/bin/sed -e "s;^\([^/]*/[^/]*/\);;g" | \
	/usr/bin/tail -1
