#!/bin/bash

say() {
	echo -e "${@}"
}

fail() {
	say "${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

usage() {
	fail "usage: ${BASH_ARGV0} rpm1"
}

[ ${#} -ne 1 ] && usage

RPM="${1}"
[ -e "${RPM}" ] || fail "File [${RPM}] does not exist"
[ -f "${RPM}" ] || fail "Path [${RPM}] is not a regular file"
[ -r "${RPM}" ] || fail "File [${RPM}] is not readable"

/usr/bin/rpm -qp --queryformat "%{RELEASE}" "${RPM}" 2>/dev/null | sed -e 's;^\(.*\.\)el;el;g'
