#!/bin/bash

set -euo pipefail
. /.functions

DEBUG="$(to_boolean "${DEBUG:-false}")"

set_or_default BASE_DIR "/app"
set_or_default SECRETS_DIR "${BASE_DIR}/secrets"
export SECRETS_DIR

${DEBUG} && set -x
REALM="$(read_setting "DOMAIN_REALM")"
USERNAME="$(read_setting "DOMAIN_USERNAME" "Administrator")"
PASSWORD="$(read_setting "DOMAIN_PASSWORD")"

${DEBUG} && set -x
exec ldapsearch -H ldaps://localhost -D "${REALM}\\${USERNAME}" -y <(echo -n "${PASSWORD}") "${@}"
